[[headers]]
for = "/*.json"
  [headers.values]
  Content-Type = "application/json"
  X-Content-Type-Options = "nosniff"

[[redirects]]
from = "/*.json"
to = "/.netlify/large-media/${matches.0}"
status = 200
force = true
